version: "3"
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.0.3-apache
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    ports:
      - 8000:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
volumes:
  dbdata: